# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LprimeC <- function(xj, y, d, r, gamma) {
    .Call('_tobitnet_LprimeC', PACKAGE = 'tobitnet', xj, y, d, r, gamma)
}

logL1 <- function(y, d, r, gamma) {
    .Call('_tobitnet_logL1', PACKAGE = 'tobitnet', y, d, r, gamma)
}

tobitnet_innerC <- function(xin, yin, cin, lambda1, lambda2, pf1, pf2, delta_init, delta_0_init = 0, gamma_init = 1, eps = 1e-7, standardize = TRUE, maxit = 1e6) {
    .Call('_tobitnet_tobitnet_innerC', PACKAGE = 'tobitnet', xin, yin, cin, lambda1, lambda2, pf1, pf2, delta_init, delta_0_init, gamma_init, eps, standardize, maxit)
}

